version: '3'
services:
  php_apache:
    build:
      context: ./php_apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql
      - redis
    links:
      - redis
  mysql:
    build:
      context: ./mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/tmp/mysql
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  smtp:
    image: schickling/mailcatcher
    container_name: 'smtp'
    ports:
      - "1080:1080"
      - "1025:1025"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server
  node:
    image: node:10
    volumes:
      - ./htdocs/node:/node
    working_dir: /node
    command:  "npm install"
    command:  "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    links:
      - redis
