version: '3'
services:
  php_apache:
    build:
      context: ./php_apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - mysql
      - redis
    links:
      - redis
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  smtp:
    image: schickling/mailcatcher
    container_name: 'smtp'
    ports:
      - "1080:1080"
      - "1025:1025"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
