version: '3'

services:
  php:
    build: ./php
    container_name: php
    volumes:
    - ../Laravel:/var/www/html

  nginx:
    image: nginx
    container_name: nginx
    environment:
       - VIRTUAL_HOST=tournament.local
       - CERT_NAME=server
    volumes:
    - ./php/logs:/var/logs/nginx
    - ../Laravel:/var/www/html
    - ./site.conf:/etc/nginx/conf.d/default.conf
    - ./ssl/server.crt:/etc/nginx/server.crt
    - ./ssl/server.key:/etc/nginx/server.key
    depends_on:
    - php
  mysql:
    image: mysql:5.7
    user: "1000:50"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    environment:
       MYSQL_DATABASE: laravel
       MYSQL_USER: laravel
       MYSQL_PASSWORD: laravel
       MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: "--innodb_use_native_aio=0"
networks:
  default:
    external:
       name: shared
