ersion: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
      - image: circleci/mysql:5.7
    environment:
      - APP_DEBUG: true
      - APP_ENV: testing
      - APP_KEY: base64:arPZRDCovVqsRNiABCSSfxnmI5woFRgEivkWzWQN0Js=
      - MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Set env
          working_directory: Laravel
          command: |
            cp .env.testing .env

      - run:
          name: Install PHP Extensions
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql

#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "Laravel/composer.json" }}
#            - v1-dependencies-

      - run:
          name: composer install
          working_directory: Laravel
          command: composer install -n --prefer-dist

#      - save_cache:
#          paths:
#            - ./vendor
#          key: v1-dependencies-{{ checksum "Laravel/composer.json" }}

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Migration & Seeding
          working_directory: Laravel
          command: php artisan migrate --seed

#      - run:
#          name: Make tourament
#          working_directory: Laravel
#          command: php artisan command:tournament 1

#      - run:
#          name: phpunit
#          working_directory: Laravel
#          command: php ./vendor/bin/phpunit
