version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-stretch-node-browsers
        environment:
        - APP_DEBUG: true
        - APP_ENV: testing
        - APP_KEY: base64:YlIJx6uH3OUb3hxN+PAiJKlC+EGZ2KYi8VHxsfdJpLk=
        - DEV_FAKER_LOCALE: ja_JP
        - DB_CONNECTION: circleci
        - MIX_NODE_HOST: tournament.local
        - MIX_NODE_PORT: 3000
        - REDIS_PORT: 6379
      - image: circleci/mysql:5.7
        environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: true
        - MYSQL_ROOT_PASSWORD: root
        - MYSQL_DATABASE: laravel
        - MYSQL_USER: laravel
        - MYSQL_PASSWORD: laravel
      - image: node:10
      - image: redis:latest
#      - image: selenium/hub:3.141.59-vanadium
#        container_name: selenium-hub
#      - image: selenium/node-chrome:3.141.59-vanadium
#        environment:
#        - HUB_HOST: 0.0.0.0
#        - HUB_PORT: 4444

    working_directory: ~/repo

    steps:


      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Laravel/composer.json" }}
            - v1-dependencies-

      - restore_cache:
          keys:
            - v1-node-{{ checksum "Laravel/node/package.json" }}
            - v1-node-

      - run:
          name: npm install
          working_directory: Laravel/node
          command: npm install

      - run:
          name: start node server
          working_directory: Laravel/node
          command: node ./bin/node_server.js &
          environment:
            - CERTS_DIR_PATH:  /home/circleci/repo/docker/node/certs/
            - REDIS_HOST: 0.0.0.0
            - REDIS_PORT: 6379

      - run:
          name: composer install
          working_directory: Laravel
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./Laravel/vendor
          key: v1-dependencies-{{ checksum "Laravel/composer.json" }}

      - save_cache:
          paths:
            - ./Laravel/node/node_modules
          key: v1-node-{{ checksum "Laravel/node/package.json" }}

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Migration & Seeding
          working_directory: Laravel
          command: php artisan migrate --seed

      - run:
          name:  Artisan command
          working_directory: Laravel
          command: php artisan command:tournament 1

      - run:
          name: Install Chrome Driver
          working_directory: Laravel
          command: php artisan dusk:chrome-driver --all
#
      - run:
          name: Start Chrome Driver
          working_directory: Laravel
          command: chmod 775 .vendor/laravel/dusk/bin/*
          command: ./vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
         name: Run Laravel Server
         working_directory: Laravel
         command: php artisan serve
         background: true

      - run:
          name:  phpunit
          working_directory: Laravel
          command: ./vendor/bin/phpunit
#
      - run:
          name:  dusk
          working_directory: Laravel
          command: php artisan dusk
