version: '3'
services:
#  php_apache:
#    build:
#      context: .
#      dockerfile: ./php_apache/Dockerfile
##    ports:
##      - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
##      - ${APP_HTTPS_PORT}:${APP_HTTPS_PORT}
#    environment:
#      - VIRTUAL_HOST=tournament.local
#      - VIRTUAL_PORT=443
#      - CERT_NAME=server
#    volumes:
#      - ../${APP_NAME}:/var/www/html
#    depends_on:
#      - mysql
#      - redis
#    links:
#      - redis
  php:
    build: ./php
    container_name: php
    volumes:
      - ../Laravel:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    external_links:
      - smtp
      - mysql5.7:mysql5.7
  nginx:
    image: nginx
    container_name: nginx
    environment:
        - VIRTUAL_HOST=tournament.local
        - CERT_NAME=server
        #    ports
#      - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
#      - ${APP_HTTPS_PORT}:${APP_HTTPS_PORT}
    volumes:
      - ./php/logs:/var/logs/nginx
      - ../Laravel:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
#      - ./certs/server.crt:/etc/nginx/server.crt
#      - ./certs/server.key:/etc/nginx/server.key
    depends_on:
      - php
#  mysql:
#    image: mysql:5.7
#    user: "1000:50"
#    volumes:
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/init:/docker-entrypoint-initdb.d
#      - ./mysql/logs:/var/log/mysql
#    environment:
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_USER: ${DB_USERNAME}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#    ports:
#      - ${DB_PORT}:3306
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    command: "--innodb_use_native_aio=0"
#  smtp:
#    image: schickling/mailcatcher
#    ports:
#      - ${MAIL_ADMIN_PORT}:${MAIL_ADMIN_PORT}
#      - ${MAIL_PORT}:${MAIL_PORT}
  redis:
    image: redis:latest
    user: "999:redis"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./redis/data:/data
    command: "redis-server --appendonly yes"
  node:
    image: node:10
    volumes:
      - ../${APP_NAME}/node:/node
      - ./certs:/ssl
    working_dir: /node
    command:  "npm install"
    command:  "npm start"
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    depends_on:
#      - mysql
      - redis
    links:
      - redis
networks:
  default:
    external:
      name: shared
