version: '3'
services:
  php:
    build: ./php
    container_name: tournament_php
    volumes:
      - ../Laravel:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /opt:/opt
    external_links:
      - smtp
#      - mysql5.7:mysql5.7
    depends_on:
      - mysql
    links:
      - mysql:mysql
  nginx:
    image: nginx
    container_name: nginx
    environment:
        - VIRTUAL_HOST=tournament.local
        - CERT_NAME=server
    volumes:
      - ./php/logs:/var/logs/nginx
      - ../Laravel:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    container_name: tournament_mysql5_7
    user: "1000:50"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    environment:
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USERNAME}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-buffer-pool-size=256M --innodb_use_native_aio=0
  redis:
    image: redis:latest
    container_name: tournament_redis
    user: "999:redis"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data

  node:
    image: node:10
    container_name: tournament_node
    volumes:
      - ../Laravel/node:/node
      - ./node/certs:/certs
    working_dir: /node
    environment:
      CERTS_DIR_PATH: /certs/
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MIX_NODE_PORT: ${MIX_NODE_PORT}
    ports:
      - ${MIX_NODE_PORT}:3000
    command: bash -c  "npm install && npm start"
    depends_on:
      - mysql
        #  - redis
        #links:
        #  - redis
networks:
  default:
    external:
      name: nginx-proxy
