version: '3'
services:
  php:
    build: ./php
    container_name: tournament_php
    volumes:
      - ../Laravel:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    external_links:
      - smtp
#      - mysql5.7:mysql5.7
    depends_on:
      - mysql
    links:
      - mysql:mysql
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
  nginx:
    image: nginx
    container_name: nginx
    environment:
        - VIRTUAL_HOST=tournament.local
        - CERT_NAME=server
        #    ports
#      - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
#      - ${APP_HTTPS_PORT}:${APP_HTTPS_PORT}
    volumes:
      - ./php/logs:/var/logs/nginx
      - ../Laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./certs/server.crt:/etc/nginx/server.crt
#      - ./certs/server.key:/etc/nginx/server.key
    links:
      - php:php
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    container_name: tournament_mysql5_7
    user: "1000:50"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql
    environment:
       MYSQL_DATABASE: ${DB_DATABASE}
       MYSQL_USER: ${DB_USERNAME}
       MYSQL_PASSWORD: ${DB_PASSWORD}
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-buffer-pool-size=256M --innodb_use_native_aio=0
#  smtp:
#    image: schickling/mailcatcher
#    ports:
#      - ${MAIL_ADMIN_PORT}:${MAIL_ADMIN_PORT}
#      - ${MAIL_PORT}:${MAIL_PORT}
  redis:
    image: redis:latest
    container_name: tournament_redis
    user: "999:redis"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data
#    command: "redis-server --appendonly yes"
  node:
    image: node:10
    container_name: tournament_node
    volumes:
      - ../Laravel/node:/node
      - ./node/certs:/certs
    working_dir: /node
    environment:
      CERTS_DIR_PATH: /certs/
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - ${MIX_NODE_PORT}:3000
    command: bash -c  "npm install && npm start"
    depends_on:
      - mysql
      - redis
    links:
      - redis
  selenium-hub:
    image: selenium/hub:3.141.59-vanadium
    container_name: selenium-hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    container_name: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
networks:
  default:
    external:
      name: nginx-proxy

#  php_apache:
#    build:
#      context: .
#      dockerfile: ./php_apache/Dockerfile
##    ports:
##      - ${APP_HTTP_PORT}:${APP_HTTP_PORT}
##      - ${APP_HTTPS_PORT}:${APP_HTTPS_PORT}
#    environment:
#      - VIRTUAL_HOST=tournament.local
#      - VIRTUAL_PORT=443
#      - CERT_NAME=server
#    volumes:
#      - ../${APP_NAME}:/var/www/html
#    depends_on:
#      - mysql
#      - redis
#    links:
#      - redis

