version: "2"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
  smtp:
    image: schickling/mailcatcher
    container_name: smtp
    ports:
      - 1080:1080
      - 1025:1025
networks:
  default:
    external:
      name: shared
